services:
  web:
    image: ${APP_IMAGE}      # Jenkins passes this
    ports:
      - "8080:80"
    environment:
      APP_ENV: ci
      DB_HOST: db
      DB_DATABASE: docker_database
      DB_USERNAME: root
      DB_PASSWORD: 12345
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: docker_database
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-uroot", "-p12345"]
      interval: 5s
      timeout: 3s
      retries: 20
